name: Build Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  docs:
    name: Build Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.6"

      - name: Install project with [docs] extras
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e ".[docs]"

      - name: Build Documentation (warnings treated as errors)
        run: |
          sphinx-build -b html docs docs/_build/html
